# Homix - Edge Server
# The ONLY container you need to run at home!

version: '3.8'

services:
  edge:
    image: ghcr.io/calmera/homix-edge:latest
    container_name: homix-edge
    restart: unless-stopped
    network_mode: host  # Required for device discovery
    
    volumes:
      # Your Synadia Cloud credentials
      - ${SYNADIA_CREDS:-~/.synadia/NGS-Home-daan.creds}:/creds/cloud.creds:ro
      
      # Persistent data (automations, device state)
      - ./data:/data
      
      # Optional: Custom configuration
      # - ./config/edge.yaml:/config/edge.yaml:ro
    
    environment:
      # Required: Your home name
      - HOME_NAME=${HOME_NAME:-My Home}
      
      # Optional: Location for sunrise/sunset
      - HOME_LAT=${HOME_LAT}
      - HOME_LON=${HOME_LON}
      - HOME_TZ=${HOME_TZ:-America/New_York}
      
      # Optional: Enable debug logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
    
    ports:
      # Local NATS (for device connections)
      - "4222:4222"
      
      # NATS monitoring
      - "8222:8222"
      
      # WebSocket (for local UI if needed)
      - "9222:9222"
      
      # MQTT bridge (for MQTT devices)
      - "1883:1883"
      
      # HTTP API (for REST devices)
      - "8080:8080"
      
      # Prometheus metrics
      - "2112:2112"

# That's it! No database, no separate UI container, no complex configuration.
# Everything else runs in the cloud.