version: '3'

# Services for Cloud-First Architecture
# Most services are now part of the edge server

includes:
  simulator: ./device-simulator/Taskfile.yaml

tasks:
  build:
    desc: Build remaining services (device simulator)
    cmds:
      - task: simulator:build

  test:
    desc: Test remaining services
    cmds:
      - task: simulator:test

  lint:
    desc: Lint remaining services
    cmds:
      - task: simulator:lint

  simulator:run:
    desc: Run device simulator for testing
    cmds:
      - task: simulator:run

  legacy:info:
    desc: Information about moved services
    cmds:
      - |
        echo "========================================="
        echo "Services Migration Information"
        echo "========================================="
        echo ""
        echo "The following services have been moved:"
        echo "• Discovery Service → Part of edge server"
        echo "• Management UI → Cloud-based (Vercel/Netlify)"
        echo "• Health Monitor → Part of edge server"
        echo "• Automation Engine → Part of edge server"
        echo ""
        echo "Only the device simulator remains as a separate service"
        echo "for testing purposes."
        echo ""
        echo "Legacy services can be found in: legacy/services/"