version: '3'

vars:
  PYTHON_CMD: '{{default "python3" .PYTHON_CMD}}'
  CONTAINER_TOOL: '{{default "docker" .CONTAINER_TOOL}}'

includes:
  zigbee: ./zigbee2mqtt-nats/Taskfile.yaml

tasks:
  default:
    desc: List available bridge tasks
    cmds:
      - task --list

  setup:
    desc: Setup bridges environment
    cmds:
      - '{{.PYTHON_CMD}} -m venv venv'
      - ./venv/bin/pip install -r requirements.txt

  build:
    desc: Build all bridges
    cmds:
      - task: zigbee:build

  mqtt-bridge:
    desc: Run MQTT to NATS bridge
    cmds:
      - cd mqtt-nats-bridge && {{.PYTHON_CMD}} -m main

  test:
    desc: Run bridge tests
    cmds:
      - |
        if {{.PYTHON_CMD}} -c "import pytest" >/dev/null 2>&1; then
          if [ -d "tests" ]; then
            {{.PYTHON_CMD}} -m pytest tests/ -v
          else
            echo "No tests directory found in bridges/"
          fi
        else
          echo "Warning: pytest not installed. Skipping Python tests."
          echo "To run tests, install pytest: pip install pytest"
        fi
      - task: zigbee:test

  lint:
    desc: Lint code
    cmds:
      - '{{.PYTHON_CMD}} -m pylint mqtt-nats-bridge/'
      - '{{.PYTHON_CMD}} -m black --check .'
      - task: zigbee:lint

  format:
    desc: Format Python code
    cmds:
      - '{{.PYTHON_CMD}} -m black .'

  clean:
    desc: Clean artifacts
    cmds:
      - find . -name "*.pyc" -delete
      - find . -name "__pycache__" -type d -exec rm -rf {} +
      - rm -rf .pytest_cache
      - rm -rf *.egg-info
      - task: zigbee:clean

  docker-build:
    desc: Build bridge Docker images
    cmds:
      - '{{.CONTAINER_TOOL}} build -t nats-mqtt-bridge:latest mqtt-nats-bridge/'

  docker-run:
    desc: Run MQTT bridge in Docker
    cmds:
      - |
        {{.CONTAINER_TOOL}} run --rm \
          -e NATS_URL=nats://host.docker.internal:4222 \
          -e MQTT_BROKER=host.docker.internal \
          --name nats-mqtt-bridge \
          nats-mqtt-bridge:latest