version: '3'

# Infrastructure tasks for cloud-first architecture
# NATS server is now part of the edge server

vars:
  CONTAINER_TOOL: '{{default "docker" .CONTAINER_TOOL}}'

tasks:
  setup:
    desc: Set up cloud-first infrastructure
    cmds:
      - |
        echo "Setting up NATS Home Automation..."
        echo ""
        echo "For the cloud-first architecture, infrastructure setup is simple:"
        echo "1. Sign up for Synadia Cloud: https://app.ngs.global"
        echo "2. Run the installer: curl -sSL https://get.nats-home.io | sh"
        echo ""
        echo "The edge server includes all necessary infrastructure:"
        echo "• NATS server (configured as leaf node)"
        echo "• JetStream for persistence"
        echo "• KV store for configuration"
        echo "• Device gateway"
        echo "• Automation engine"

  test-connection:
    desc: Test connection to Synadia Cloud
    cmds:
      - ../scripts/test-cloud-connection.sh {{.CREDS}}
    vars:
      CREDS: '{{default "~/.synadia/NGS-Home-*.creds" .CREDS}}'

  edge:logs:
    desc: View edge server logs
    cmds:
      - '{{.CONTAINER_TOOL}} logs -f nats-home-edge'

  edge:status:
    desc: Check edge server status
    cmds:
      - '{{.CONTAINER_TOOL}} ps | grep nats-home-edge || echo "Edge server not running"'

  legacy:up:
    desc: Start legacy local NATS server (for development/testing)
    cmds:
      - |
        echo "Starting legacy NATS server..."
        echo "Note: This is only for development/testing of legacy components"
        {{.CONTAINER_TOOL}} run -d \
          --name nats-legacy \
          -p 4222:4222 -p 8222:8222 \
          -v ./legacy/infrastructure/nats-server-dev.conf:/etc/nats/nats-server.conf:ro \
          nats:2.11 -c /etc/nats/nats-server.conf

  legacy:down:
    desc: Stop legacy NATS server
    cmds:
      - '{{.CONTAINER_TOOL}} stop nats-legacy || true'
      - '{{.CONTAINER_TOOL}} rm nats-legacy || true'

  clean:
    desc: Clean up all infrastructure containers
    cmds:
      - '{{.CONTAINER_TOOL}} stop nats-home-edge || true'
      - '{{.CONTAINER_TOOL}} rm nats-home-edge || true'
      - '{{.CONTAINER_TOOL}} stop nats-legacy || true'
      - '{{.CONTAINER_TOOL}} rm nats-legacy || true'

  legacy:info:
    desc: Information about infrastructure changes
    cmds:
      - |
        echo "========================================="
        echo "Infrastructure Migration Information"
        echo "========================================="
        echo ""
        echo "OLD ARCHITECTURE:"
        echo "• Separate NATS server container"
        echo "• Separate init container"
        echo "• Complex configuration files"
        echo "• Multiple networks and volumes"
        echo ""
        echo "NEW ARCHITECTURE:"
        echo "• NATS server built into edge server"
        echo "• Auto-configuration on startup"
        echo "• Single container deployment"
        echo "• Cloud-based management"
        echo ""
        echo "To migrate:"
        echo "1. Export your data (if needed)"
        echo "2. Set up Synadia Cloud"
        echo "3. Run: task install"